title: "Unified Compliance Framework"
main_navigation:
    Education: "education.html"
    Developer Docs: "https://developer.unifiedcompliance.com/"
    Common Controls Hub: "https://commoncontrolshub.com/overview/"
    Contributing: "contributing.html"
    Join Slack: "mailto:dcougias@unifiedcompliance.com"

sass:
    sass_dir: _sass
    style: compresed

exclude:
    - .idea
    - bower_components
    - node_modules
    - sass