title: "Unified Compliance Framework"
main_navigation:
    Home: "index.html"
    About: "https://www.unifiedcompliance.com/company/"
    Developer Docs: "developer.html"
    Education: "education.html"
    Join Us on Slack: "mailto:dcougias@unifiedcompliance.com"
    Common Controls Hub: "https://commoncontrolshub.com/overview/"

exclude:
    - .idea
    - bower_components
    - node_modules
    - sass