title: "Unified Compliance Framework"
main_navigation:
    Home: "index.html"
    Education: "education.html"
    Developer Docs: "https://developer.unifiedcompliance.com/"
    About: "https://www.unifiedcompliance.com/company/"
    Join Us on Slack: "mailto:dcougias@unifiedcompliance.com"
    Common Controls Hub: "https://commoncontrolshub.com/overview/"

sass:
    sass_dir: _sass
    style: compresed

exclude:
    - .idea
    - bower_components
    - node_modules
    - sass